### PR TITLE
fix xs check not reporting vec and str concatination error

### LINKED ISSUE #17: xs-check does not catch errors when adding a left side vector to a right side string
Adding a string to the vector is an error if the vector is on the left side of the expression, but it's ok if it's on the right. xs-check does not catch this error.

eg:
```c
void main() {
    vector v = vector(1.1, 2.2, 3.3);
    string s = "hello";
    string r1 = s + v; /* <- ok */
    string r2 = v + s; /* <- error */
}
```

aoe2 error:

Image

### PR DESCRIPTION
**Pull request by mardaravicius**
attempt fix for:
https://github.com/Divy1211/xs-check/issues/17

### CODE REVIEW

File: xsc-core/src/static/type_check/util.rs [hunk 1]
```diff
@@ -128,7 +128,8 @@ pub fn arith_op(
 
         (Type::Float, Type::Int | Type::Float) => { Some(Type::Float) }
 
-        (Type::Str, _) | (_, Type::Str) if op_name == "add" => { Some(Type::Str) }
+        (Type::Str, Type::Int | Type::Float | Type::Bool | Type::Str | Type::Vec) if op_name == "add" => { Some(Type::Str) }
```
Comment (Divy1211) [inline xsc-core/src/static/type_check/util.rs]: do `(Type::Str, _)` for this first pattern

**Review by Divy1211 — CHANGES_REQUESTED** [review]

**Review by Divy1211 — APPROVED** [review]

**Comment by Divy1211** [comment]
Thanks for the fix!
